name: SonarCloud
on:
  push:
    branches: [main, test]
  pull_request:
    branches: [main, test]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Compile
        run: ./gradlew compileJava
      - name: Test
        run: ./gradlew test
      - name: Jar
        run: ./gradlew bootJar
      - name: analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN  }}
          DB_URL: ${{ secrets.DB_URL_PRODUCTION }}
          DB_NAME: ${{ secrets.DB_NAME_PRODUCTION }}
          DB_USERNAME: ${{ secrets.DB_USERNAME_PRODUCTION }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD_PRODUCTION }}
        run: ./gradlew sonarqube --info
